Revise SDL-0293 Enable OEM exclusive apps support
smartdevicelink/sdl_evolution pull request #1092
Opened 2020-11-11 15:52 UTC by ashwink11

This feature will enable SDL adopters to provide exclusive apps to their users depending on vehicle type. The proposal describes a way to share vehicle type information before sending the Register App Interface request.

@theresalech I made changes as per SDLC review comments. In addition to that, I also added the "HMI Changes" section. Could you please review this PR?

2020-11-12 18:01 UTC, theresalech requested changes
Hi @ashwink11, thanks for your PR! I've left comments, questions, and suggested changes in my review. Additionally, it doesn't appear that Item 3 from the [requested revisions](https://github.com/smartdevicelink/sdl_evolution/issues/971#issuecomment-724280199) is reflected in this PR:

(In the `Impact on existing code` section)
>Above mentioned changes need to be implemented in SDL Core, the Java Suite app library, and the iOS app library.

Update to "Above mentioned changes need to be implemented in SDL Core, the Java Suite app library, the iOS app library, and the JavaScript Suite app library."

--

Please add and tag @pelsila when this PR is ready for re-review, as I will be on leave beginning 2020-11-17. Thank you!

2020-11-13 08:12 UTC, ashwink11 commented on proposals/0293-vehicle-type-filter.md
> +8. The callback function will notifiy application layer only once when vehicle type info is available. If the function is called after `StartServiceACK` protocol message is received, it will not be c
Changes added in commit - 34785fb

2020-11-13 08:12 UTC, ashwink11 commented on proposals/0293-vehicle-type-filter.md
> +2. On receiving vehicle type information, the libraries will use below callback function to notify application layer.
Changes added in commit - 34785fb

2020-11-13 08:13 UTC, ashwink11 commented on proposals/0293-vehicle-type-filter.md
> +### HMI Changes
Removed in commit - 34785fb

2020-11-13 08:13 UTC, ashwink11 commented on proposals/0293-vehicle-type-filter.md
> +* Impacted Platforms: [Core / iOS / Java Suite / Protocol / JavaScript Suite / Web-HMI]
Removed in commit - 34785fb

2020-11-13 08:14 UTC, ashwink11 commented
@theresalech Thank you for the review.
@pelsila I have added changes as per the review comments. Could you please review this PR?

2020-11-16 16:10 UTC, theresalech requested changes
@ashwink11, thank you for the quick response! I have verified changes, and provided two more suggestions based on your latest commit. @pelsila will review this PR moving forward, so please make sure he is tagged again when this is ready for re-review. Thanks!

2020-11-16 16:10 UTC, theresalech commented on proposals/0293-vehicle-type-filter.md
> +2. If the `StartServiceACK` comes in with vehicle data, the below method will be called with the vehicle type information. If the developer responds `true`, the session continues, if `false`, the ses
```suggestion
2. If the `StartServiceACK` comes in with vehicle data, the below method will be called with the vehicle type information. If the developer responds `true`, the session continues, if `false`, the session ends with an `EndService` sent by the library. When the `RegisterAppInterfaceResponse` happens, the below method will not be called a second time. 
```

2020-11-17 07:33 UTC, ashwink11 commented
@theresalech @pelsila 
I have added changes as per the suggestions. Could you please review this PR?

2020-11-17 15:53 UTC, pelsila approved these changes

2020-11-18 16:10 UTC, merged