App Library Remote Control Manager
smartdevicelink/sdl_evolution pull request #1093
Opened 2020-11-17 21:05 UTC by joeljfischer

This proposal adds a remote control manager to the app libraries which manages everything related to the remote control systems on head units and allows apps to more conveniently retrieve and set remote control data.

2020-11-17 21:07 UTC, joeljfischer commented
@pelsila This proposal is ready for review

2020-11-19 14:55 UTC, pelsila requested changes
@joeljfischer Just one minor suggestion.  Let me know if you have any questions.  Thank you

2020-11-19 14:55 UTC, pelsila commented on proposals/nnnn-app-lib-remote-control-manager.md
> +On RPC 6.0+ systems, an app may be required to request access to a remote control module from the user, but it should only do when it actually needs that access. The developer will be able to request
```suggestion
On RPC 6.0+ systems, an app may be required to request access to a remote control module from the user, but only when it actually needs that access. The developer will be able to request user consent manually for a module or modules whenever it makes sense within their app's flow.
```

2020-11-20 13:17 UTC, joeljfischer commented
@pelsila Committed the suggestion, thank you for the review.

2020-11-20 14:25 UTC, pelsila approved these changes

2020-11-25 16:07 UTC, merged