OnDataResumed Notification
smartdevicelink/sdl_evolution pull request #1096
Opened 2020-11-19 15:14 UTC by JackLivio

This proposal creates a new RPC notification that relays app resumption info from SDL Core to the mobile app after registration. The notification is named `OnDataResumed`.

2020-11-19 15:14 UTC, JackLivio commented
@pelsila Ready for review

2020-11-20 15:36 UTC, pelsila requested changes
@JackLivio Just one typo.  Let me know if you have any questions.  Thank you

2020-11-20 15:36 UTC, pelsila commented on proposals/nnnn-on-data-resumed.md
> +* Author: [JacLivio](https://github.com/JackLivio)
```suggestion
* Author: [JackLivio](https://github.com/JackLivio)
```

2020-11-23 18:25 UTC, JackLivio commented
@pelsila Updated

2020-11-23 18:31 UTC, pelsila approved these changes

2021-02-03 16:53 UTC, merged