Modernize Ubuntu Support V20 LTS
smartdevicelink/sdl_evolution pull request #1097
Opened 2020-11-23 21:39 UTC by JackLivio

This proposal would like to provide support for Ubuntu 20 LTS and bump the minimum required version of Ubuntu 16 LTS to Ubuntu 18 LTS. Currently Ubuntu 18 is the recommended platform and Ubuntu 16 is the minimum required version.

These changes will mainly affect the build process for SDL Core and ATF.

2020-11-23 21:40 UTC, JackLivio commented
@pelsila Ready for review

2020-11-24 17:40 UTC, pelsila requested changes
@JackLivio please see suggested changes.  Thank you.

2020-11-24 17:40 UTC, pelsila commented on proposals/nnnn-modernize-ubuntu-support-v20.md
> +* Author: [Jack Byrne](https://github.com/JacLivio)
```suggestion
* Author: [Jack Byrne](https://github.com/JackLivio)
```

2020-11-24 17:40 UTC, pelsila commented on proposals/nnnn-modernize-ubuntu-support-v20.md
> +Ubuntu 16 will lose support on April 30th 2021, therefore it is important that we update the minimum required version for using SDL Core and related platforms that use a linux environment.
```suggestion
Ubuntu 16 will lose support on April 30, 2021, therefore it is important that we update the minimum required version for using SDL Core and related platforms that use a linux environment.
```

2020-11-24 17:40 UTC, pelsila commented on proposals/nnnn-modernize-ubuntu-support-v20.md
> +This type of proposal needs to be entered for every couple of years to keep up with new versions and retire older environments.
```suggestion
This type of proposal needs to be entered every couple of years to keep up with new versions and retire older environments.
```

2020-11-24 17:40 UTC, pelsila commented on proposals/nnnn-modernize-ubuntu-support-v20.md
> +An additional note is that Ubuntu 20 comes installed with only Python3 (no 2.7), but this should not be an issue as all of the support scripts used by SDL Core have been updated to use python3 in a p
```suggestion
An additional note is that Ubuntu 20 comes installed with only Python3 (not 2.7), but this should not be an issue as all of the support scripts used by SDL Core have been updated to use python3 in a previous release.
```

2020-11-24 17:40 UTC, pelsila commented on proposals/nnnn-modernize-ubuntu-support-v20.md
> +Updates may be needed to the build scripts used in SDL Core and ATF. Any run time issues will need to be fixed. Runtime issues will be discovered via a full regression test run via ATF.
```suggestion
Updates may be needed to the build scripts used in SDL Core and ATF. Any runtime issues will need to be fixed. Runtime issues will be discovered via a full regression test run via ATF.
```

2020-11-25 16:53 UTC, JackLivio commented
@pelsila thank you for the review. Suggestions were applied.

2020-11-30 14:24 UTC, pelsila approved these changes

2020-12-09 16:27 UTC, merged