Additional Video Streaming Capabilities Validation
smartdevicelink/sdl_evolution pull request #1133
Opened 2021-04-27 20:45 UTC by JackLivio

This proposal is an extension of an already implemented proposal: SDL 0296 - Possibility to update video streaming capabilities during ignition cycle. This proposal will define some extra validation rules to the capabilities the HMI and SDL Apps send to SDL Core to prevent malformed video streaming capabilities.

2021-04-27 20:45 UTC, JackLivio commented
@theresalech Ready for review

2021-04-28 17:44 UTC, theresalech requested changes
Hi @JackLivio, I've completed my review. Please let me know if you have any questions or concerns with addressing my feedback. Thank you!

2021-04-29 19:44 UTC, JackLivio commented
@theresalech Ready for review.

2021-04-29 20:22 UTC, theresalech approved these changes

2021-05-12 15:10 UTC, merged