Transform SetDisplayLayout requests into UI.Show for HMIs
smartdevicelink/sdl_evolution pull request #1136
Opened 2021-04-30 14:02 UTC by ShobhitAd

This proposal is to make modifications in sdl_core to transform incoming `SetDisplayLayout` requests from applications into `UI.Show` requests to send to the HMI.

2021-04-30 18:55 UTC, ShobhitAd commented
@theresalech Ready for review

2021-05-03 13:09 UTC, theresalech requested changes
Hi @ShobhitAd - I've left two minor suggested changes. Please let me know if you have any questions. Thanks!

2021-05-03 13:09 UTC, theresalech commented on proposals/nnnn-transform-setdisplaylayout-requests-to-ui-show.md
> +#### Change 1: Construct UI.Show request from SetDisplayLayout params
```suggestion
#### Change 1: Construct `UI.Show` request from `SetDisplayLayout` params
```

2021-05-03 13:09 UTC, theresalech commented on proposals/nnnn-transform-setdisplaylayout-requests-to-ui-show.md
> +A `SetDisplayLayout` request can be transformed into a `UI.Show` request by using the `displayLayout`,`dayColorScheme`, `nightColorScheme` parameters from the original request in the `templateConfigu
```suggestion
A `SetDisplayLayout` request can be transformed into a `UI.Show` request by using the `displayLayout`,`dayColorScheme`, `nightColorScheme` parameters from the original request in the `templateConfiguration` struct for the `UI.Show` request.
```

2021-05-04 14:50 UTC, theresalech approved these changes

2021-05-12 15:29 UTC, merged