Revise SDL 0317 - SDL Protocol Security Specification
smartdevicelink/sdl_evolution pull request #1153
Opened 2021-06-09 18:45 UTC by dboltovskyi

Revised proposal based on review comments (see https://github.com/smartdevicelink/sdl_evolution/issues/1070#issuecomment-857760129)

### Updates
 - Updated section "Change 1: Update Frame Header Fields description": Removed changes related to "Frame Info"
 - Updated section "4.2.5 Start Service": Added section number for "Secured Communication"
 - Updated section "7. Secured Communication": Added details on re-starting of service
 - Updated section "Impact on existing code": Removed any impact except "Protocol specification"
 - Updated section "Impacted Platforms": Removed everything except "Protocol"

2021-06-09 18:46 UTC, dboltovskyi commented
@theresalech Please notice PR is ready for PM review.

2021-06-09 20:09 UTC, theresalech requested changes
@dboltovskyi I've suggested one minor change. Can you please update? Let me know if you have any questions. Thank you!

2021-06-09 21:02 UTC, dboltovskyi commented
@theresalech Thank you for your review. Suggested change is applied in 244f788c4084767f1b4ea962ee8ce41f221cd836

2021-06-10 14:48 UTC, theresalech approved these changes

2021-06-10 14:49 UTC, merged