Revise SDL 0333 - Handle Scenario Where no Valid Cert is Available
smartdevicelink/sdl_evolution pull request #1159
Opened 2021-06-24 15:02 UTC by iCollin

Revisions to proposal 0333 per [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1140#issuecomment-866803388)

2021-06-24 15:02 UTC, iCollin commented
@theresalech this PR is ready for review

2021-06-28 15:04 UTC, theresalech requested changes
Hi @iCollin, I've suggested a few small formatting changes. Please let me know if you have any questions or concerns with my feedback. Thank you!

2021-06-29 13:33 UTC, iCollin commented on proposals/0333-handle-scenario-where-no-valid-cert-is-available.md
> +|encryptionReady Value|App Action|
IMO code tags in the table header make this harder to read and I think it looks better without code tags. If you think it is proper let me know and I will commit this suggestion as well.

2021-06-29 15:11 UTC, theresalech approved these changes

2021-06-30 14:44 UTC, merged