SDL 0340 Revisions
smartdevicelink/sdl_evolution pull request #1169
Opened 2021-07-29 19:06 UTC by JackLivio

Agreed upon revisions from this [comment](https://github.com/smartdevicelink/sdl_evolution/issues/1164#issuecomment-887725323)

2021-07-29 19:06 UTC, JackLivio commented
@theresalech Ready for review

2021-07-29 20:00 UTC, theresalech requested changes
Hi @JackLivio, these revisions look good. I've just suggested a few minor changes. Please let me know if you have any questions. Thanks!

2021-07-30 16:02 UTC, JackLivio commented
@theresalech Ready for re-review

2021-08-02 00:27 UTC, theresalech approved these changes

2021-08-04 00:04 UTC, merged