Revise SDL-0339 Replace thread::Thread implementation with std::thread from C++11
smartdevicelink/sdl_evolution pull request #1171
Opened 2021-08-03 18:36 UTC by VadymLuchko

Revised proposal based on review comments (see https://github.com/smartdevicelink/sdl_evolution/issues/1163#issuecomment-887783566 )

## Updates

- Version change mentioned
- Removed clause on replacing synchronization primitives
- Added example of stopping thread
- Edited clause about changing stack size

2021-08-03 18:37 UTC, VadymLuchko commented
@theresalech Ready for review

2021-08-03 19:09 UTC, theresalech requested changes
Hi @VadymLuchko, I've suggested two minor changes. Please let me know if you have any questions or concerns with addressing my feedback. Thank you!

2021-08-03 19:09 UTC, theresalech commented on proposals/0339-replace-pthread-implementation-with-threads-from-cpp11.md
> +However in SDL Core we don't need to specify a stack size. Since the default stack size meets SDL Core requirements.
```suggestion
However in SDL Core we don't need to specify a stack size since the default stack size meets SDL Core requirements.
```

2021-08-03 19:09 UTC, theresalech commented on proposals/0339-replace-pthread-implementation-with-threads-from-cpp11.md
> +The thread approach of SDL Core will be impacted. Removing the current thread implementation, delegate classes, and public methods will be done, a major version change of SDL Core is required.
```suggestion
The thread approach of SDL Core will be impacted. Removing the current thread implementation, delegate classes, and public methods will be done. Therefore, a major version change of SDL Core is required.
```

2021-08-04 15:47 UTC, theresalech approved these changes

2021-08-18 00:40 UTC, merged