Revise SDL-0341 - Add Generic HMI Plugin Support (again)
smartdevicelink/sdl_evolution pull request #1182
Opened 2022-01-06 20:41 UTC by jacobkeeler

Revised proposal based on review comments (see https://github.com/smartdevicelink/sdl_evolution/issues/1168#issuecomment-964475414)

## Updates

- Add full definition for configuration file format
- Finalize inter-component message format and include API definitions for all RPCs
- Update wording throughout proposal to be more concrete, finalize several implementation details
- Clarify that all test plugins will be included directly in the repository

2022-01-06 20:46 UTC, jacobkeeler commented
@theresalech Ready for review

2022-01-10 16:52 UTC, theresalech requested changes
Hi @jacobkeeler, I've suggested a few minor changes. Please review and let me know if you have any questions or concerns with applying my feedback. Thanks!

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +* MiscPlugins (Plugin array) - List of configurations for plugins are not tied to a specific HMI interface (such as the [General Settings](#general-settings-plugin) plugin or [Phone](#phone-plugin) p
```suggestion
* MiscPlugins (Plugin array) - List of configurations for plugins which are not tied to a specific HMI interface (such as the [General Settings](#general-settings-plugin) plugin or [Phone](#phone-plugin) plugin).
```

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +        <description>ID of the application requested this RPC.</description>
```suggestion
        <description>ID of the application that requested this RPC.</description>
```

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +       <description>'true' when the event is started, 'false' when the event has ended</description>
```suggestion
       <description>'true' when the event is started, 'false' when the event has ended.</description>
```

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +* `DEACTIVATE_HMI` - the request will be sent to the `BasicCommunication` interface (and handled by the General Settings plugin.
```suggestion
* `DEACTIVATE_HMI` - the request will be sent to the `BasicCommunication` interface (and handled by the General Settings plugin).
```

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +      <description>SoftButtons to display with popup.</description>
```suggestion
      <description>SoftButtons to display with the popup.</description>
```

2022-01-10 16:52 UTC, theresalech commented on proposals/0341-add-generic-hmi-plugin-support.md
> +With the variety of components being added in this proposal which run separate from the main HMI, a startup script will be required to handle the initialization of all of these components. This scrip
```suggestion
With the variety of components being added in this proposal which run separate from the main HMI, a startup script will be required to handle the initialization of all of these components. This script will start the HMI, python backend, and any desired plugins all at once using a single command. This new script will need its own simple configuration file in order to start each plugin, for example:
```

2022-01-10 19:11 UTC, jacobkeeler commented on proposals/0341-add-generic-hmi-plugin-support.md
> +        <description>ID of the application requested this RPC.</description>
```suggestion
        <description>ID of the application which requested this RPC.</description>
```

2022-01-10 20:42 UTC, theresalech approved these changes

2022-01-12 00:07 UTC, merged